services:
  support-sphere:
    image: hacktifytechnologies/support-sphere:1.0
    container_name: support-sphere
    ports:
      - "8089:8087"
    restart: unless-stopped
    environment:
      NODE_ENV: production
